@startuml
title Template Transform\nState Diagram
scale 2
start
:Validate transform template config against transform schema definition;
:Emulate a media file received from an endpoint;
:Convert raw media file to xlsx workbook;
:Run transformation engine;
while (if cookie?) is (is invalid)
:Show login form;
endwhile
fork
:Mail invoice;
fork again
:Load games;
end fork
:Process the result;
stop
@enduml